# Generated by Django 3.2.25 on 2026-09-16 18:04

from django.db import migrations, models
import django_prometheus.models


class Migration(migrations.Migration):

    dependencies = [
        ("api_general", "0003_auto_20211005_0015"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardCard",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "position",
                    models.PositiveIntegerField(default=0, verbose_name="Position"),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True, verbose_name="Shown on the dashboard"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("icon", models.CharField(max_length=100, verbose_name="Icon")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description (HTML)"),
                ),
                (
                    "links",
                    models.JSONField(blank=True, default=list, verbose_name="Links"),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("dashboard-card"),
                models.Model,
            ),
        ),
    ]
