"""Pure accessors for Stripe webhook/API payloads.

Deliberately free of Django models and DB access so `api_admin_tools` can
import these without creating a cycle back through `api_billing.views`.
"""

from datetime import datetime
from datetime import timezone as dt_timezone

from django.utils import timezone


def invoice_subscription_id(invoice_data):
    # Stripe API 2025-03-31.basil moved Invoice.subscription to
    # Invoice.parent.subscription_details.subscription. Pick whichever the
    # payload actually exposes so a webhook endpoint signed with either API
    # version works. The `in details` check (rather than truthiness) means an
    # explicit `null` in the new schema is honored as "no subscription on this
    # invoice" instead of silently falling back to the legacy field.
    parent = invoice_data.get("parent") or {}
    details = parent.get("subscription_details") or {}
    if "subscription" in details:
        return details["subscription"]
    return invoice_data.get("subscription")


def invoice_billing_reason(invoice_data):
    return invoice_data.get("billing_reason")


def invoice_will_retry(invoice_data):
    """True when Stripe intends another automatic collection attempt.

    Only meaningful for charge_automatically invoices; send_invoice ones are
    never auto-retried, so this is always False for them.
    """
    return invoice_data.get("next_payment_attempt") is not None


def invoice_is_past_due(invoice_data, now=None):
    """True when the invoice's due date has passed.

    send_invoice invoices carry a due_date; charge_automatically ones do not,
    and are never past due in this sense.
    """
    due_date = invoice_data.get("due_date")
    if due_date is None:
        return False
    reference = now if now is not None else timezone.now()
    return due_date < int(reference.timestamp())


def format_invoice_due_date(invoice_data):
    """Render an invoice due date in the site's timezone, or None.

    Stripe sends unix seconds; rendering them naively would show a date a day
    out for members east of UTC.
    """
    due_date = invoice_data.get("due_date")
    if due_date is None:
        return None

    utc = datetime.fromtimestamp(due_date, tz=dt_timezone.utc)
    return timezone.localtime(utc).strftime("%d %b %Y")


def format_invoice_amount(invoice_data, prefer="paid", fallback="your membership fee"):
    """Render an invoice total for member-facing copy, e.g. "12.50 AUD".

    Pass prefer="due" for an invoice that has not been paid: Stripe reports
    amount_paid as 0 rather than null on those, so preferring it would quote
    "0.00" for what is still owed.

    Falls back to a bare description when the payload carries no usable
    amount, so an email is still sent rather than one reading "$None". Member
    copy passes the description in the member's language.
    """
    fields = (
        ("amount_due", "amount_paid")
        if prefer == "due"
        else ("amount_paid", "amount_due")
    )
    amount = next(
        (invoice_data[f] for f in fields if invoice_data.get(f) is not None),
        None,
    )
    if amount is None:
        return fallback

    currency = (invoice_data.get("currency") or "").upper()
    formatted = f"{amount / 100:.2f}"
    return f"{formatted} {currency}".strip()


def is_subscription_invoice(invoice_data):
    """True when Stripe says this invoice was generated by a subscription.

    Covers subscription_create / subscription_cycle / subscription_update /
    subscription_threshold, and excludes one-off charges ("manual").
    """
    return (invoice_billing_reason(invoice_data) or "").startswith("subscription")
