# Generated by Django 3.2.25 on 2026-10-08 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api_admin_tools", "0013_paymentplan_description"),
        ("api_billing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanPriceChange",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_price_id", models.CharField(max_length=100)),
                ("new_price_id", models.CharField(max_length=100)),
                ("old_cost", models.IntegerField(verbose_name="Old cost in cents")),
                ("new_cost", models.IntegerField(verbose_name="New cost in cents")),
                ("currency", models.CharField(max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("partial", "Partial"),
                            ("interrupted", "Interrupted"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("runs", models.PositiveIntegerField(default=0)),
                ("migrated_count", models.PositiveIntegerField(default=0)),
                ("remaining_count", models.PositiveIntegerField(default=0)),
                ("failures", models.JSONField(blank=True, default=list)),
                ("error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_changes",
                        to="api_admin_tools.paymentplan",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
            },
        ),
    ]
